apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Values.url }}
  labels:
    app.kubernetes.io/part-of: tum-sexy
  namespace: {{ $.Values.namespace }}
spec:
  commonName: {{ $.Values.url }}
  dnsNames:
    - {{ $.Values.url }}
  secretName: {{ $.Values.url }}
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
