name: Update Dockerfiles

on:
  schedule:
    - cron:  '40 16 * * *'
jobs:
  deploy:
    name: Update Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v2

      - name: 📤 Update Dockerfiles
        uses: ludeeus/dockerfile-updater@21.01.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
